// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
)

type Devices struct {
	ID          string          `json:"id"`
	NodeID      string          `json:"node_id"`
	Version     string          `json:"version"`
	Label       string          `json:"label"`
	Description string          `json:"description"`
	Tags        json.RawMessage `json:"tags"`
	Type        string          `json:"type"`
	Senders     json.RawMessage `json:"senders"`
	Receivers   json.RawMessage `json:"receivers"`
	Controls    json.RawMessage `json:"controls"`
}

type Flows struct {
	ID                     string          `json:"id"`
	SourceID               string          `json:"source_id"`
	DeviceID               string          `json:"device_id"`
	Version                string          `json:"version"`
	Label                  string          `json:"label"`
	Description            string          `json:"description"`
	Tags                   json.RawMessage `json:"tags"`
	Format                 string          `json:"format"`
	MediaType              sql.NullString  `json:"media_type"`
	SampleRate             json.RawMessage `json:"sample_rate"`
	BitDepth               sql.NullInt64   `json:"bit_depth"`
	DidSdid                json.RawMessage `json:"did_sdid"`
	GrainRate              json.RawMessage `json:"grain_rate"`
	FrameWidth             sql.NullInt64   `json:"frame_width"`
	FrameHeight            sql.NullInt64   `json:"frame_height"`
	InterlaceMode          sql.NullString  `json:"interlace_mode"`
	Colorspace             sql.NullString  `json:"colorspace"`
	Components             json.RawMessage `json:"components"`
	TransferCharacteristic sql.NullString  `json:"transfer_characteristic"`
}

type Nodes struct {
	ID          string          `json:"id"`
	Version     string          `json:"version"`
	Label       string          `json:"label"`
	Description string          `json:"description"`
	Tags        json.RawMessage `json:"tags"`
	Href        string          `json:"href"`
	Hostname    sql.NullString  `json:"hostname"`
	Api         json.RawMessage `json:"api"`
	Caps        json.RawMessage `json:"caps"`
	Services    json.RawMessage `json:"services"`
	Clocks      json.RawMessage `json:"clocks"`
	Interfaces  json.RawMessage `json:"interfaces"`
	LastSeen    sql.NullTime    `json:"last_seen"`
}

type Receivers struct {
	ID                   string          `json:"id"`
	DeviceID             string          `json:"device_id"`
	Version              string          `json:"version"`
	Label                string          `json:"label"`
	Description          string          `json:"description"`
	Tags                 json.RawMessage `json:"tags"`
	Transport            string          `json:"transport"`
	Format               string          `json:"format"`
	Caps                 json.RawMessage `json:"caps"`
	InterfaceBindings    json.RawMessage `json:"interface_bindings"`
	SubscriptionSenderID sql.NullString  `json:"subscription_sender_id"`
	SubscriptionActive   sql.NullBool    `json:"subscription_active"`
}

type Senders struct {
	ID                     string          `json:"id"`
	DeviceID               string          `json:"device_id"`
	FlowID                 sql.NullString  `json:"flow_id"`
	Version                string          `json:"version"`
	Label                  string          `json:"label"`
	Description            string          `json:"description"`
	Tags                   json.RawMessage `json:"tags"`
	Transport              string          `json:"transport"`
	ManifestHref           sql.NullString  `json:"manifest_href"`
	InterfaceBindings      json.RawMessage `json:"interface_bindings"`
	SubscriptionReceiverID sql.NullString  `json:"subscription_receiver_id"`
	SubscriptionActive     sql.NullBool    `json:"subscription_active"`
}

type Sources struct {
	ID          string          `json:"id"`
	DeviceID    string          `json:"device_id"`
	Version     string          `json:"version"`
	Label       string          `json:"label"`
	Description string          `json:"description"`
	Tags        json.RawMessage `json:"tags"`
	GrainRate   json.RawMessage `json:"grain_rate"`
	Format      string          `json:"format"`
	Caps        json.RawMessage `json:"caps"`
	Parents     json.RawMessage `json:"parents"`
	ClockName   sql.NullString  `json:"clock_name"`
}

type Subscriptions struct {
	ID              string          `json:"id"`
	ResourcePath    string          `json:"resource_path"`
	Params          json.RawMessage `json:"params"`
	MaxUpdateRateMs sql.NullInt64   `json:"max_update_rate_ms"`
	Persist         sql.NullBool    `json:"persist"`
	SecureWebsocket sql.NullBool    `json:"secure_websocket"`
	WsHref          sql.NullString  `json:"ws_href"`
}
