// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateDevice(ctx context.Context, arg CreateDeviceParams) error
	CreateFlow(ctx context.Context, arg CreateFlowParams) error
	CreateNode(ctx context.Context, arg CreateNodeParams) error
	CreateReceiver(ctx context.Context, arg CreateReceiverParams) error
	CreateSender(ctx context.Context, arg CreateSenderParams) error
	CreateSource(ctx context.Context, arg CreateSourceParams) error
	DeleteDevice(ctx context.Context, id string) error
	DeleteFlow(ctx context.Context, id string) error
	DeleteNode(ctx context.Context, id string) error
	DeleteReceiver(ctx context.Context, id string) error
	DeleteSender(ctx context.Context, id string) error
	DeleteSource(ctx context.Context, id string) error
	GetDevice(ctx context.Context, id string) (Devices, error)
	GetExpiredNodes(ctx context.Context, expirationTime sql.NullTime) ([]string, error)
	GetFlow(ctx context.Context, id string) (Flows, error)
	GetNode(ctx context.Context, id string) (Nodes, error)
	GetReceiver(ctx context.Context, id string) (Receivers, error)
	GetSender(ctx context.Context, id string) (Senders, error)
	GetSource(ctx context.Context, id string) (Sources, error)
	ListDevices(ctx context.Context) ([]Devices, error)
	ListDevicesByNode(ctx context.Context, nodeID string) ([]Devices, error)
	ListFlows(ctx context.Context) ([]Flows, error)
	ListFlowsByDevice(ctx context.Context, deviceID string) ([]Flows, error)
	ListFlowsBySource(ctx context.Context, sourceID string) ([]Flows, error)
	ListNodes(ctx context.Context) ([]Nodes, error)
	ListReceivers(ctx context.Context) ([]Receivers, error)
	ListReceiversByDevice(ctx context.Context, deviceID string) ([]Receivers, error)
	ListSenders(ctx context.Context) ([]Senders, error)
	ListSendersByDevice(ctx context.Context, deviceID string) ([]Senders, error)
	ListSendersByFlow(ctx context.Context, flowID sql.NullString) ([]Senders, error)
	ListSources(ctx context.Context) ([]Sources, error)
	ListSourcesByDevice(ctx context.Context, deviceID string) ([]Sources, error)
	UpdateDevice(ctx context.Context, arg UpdateDeviceParams) error
	UpdateFlow(ctx context.Context, arg UpdateFlowParams) error
	UpdateNode(ctx context.Context, arg UpdateNodeParams) error
	UpdateNodeLastSeen(ctx context.Context, arg UpdateNodeLastSeenParams) error
	UpdateReceiver(ctx context.Context, arg UpdateReceiverParams) error
	UpdateSender(ctx context.Context, arg UpdateSenderParams) error
	UpdateSource(ctx context.Context, arg UpdateSourceParams) error
	UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error
	UpsertFlow(ctx context.Context, arg UpsertFlowParams) error
	UpsertNode(ctx context.Context, arg UpsertNodeParams) error
	UpsertReceiver(ctx context.Context, arg UpsertReceiverParams) error
	UpsertSender(ctx context.Context, arg UpsertSenderParams) error
	UpsertSource(ctx context.Context, arg UpsertSourceParams) error
}

var _ Querier = (*Queries)(nil)
