// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createDevice = `-- name: CreateDevice :exec
INSERT INTO devices (
    id, api_version, node_id, version, label, description, tags, type, senders, receivers, controls
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6,
    ?7, ?8, ?9, ?10, ?11
)
`

type CreateDeviceParams struct {
	ID          string          `json:"id"`
	ApiVersion  string          `json:"api_version"`
	NodeID      string          `json:"node_id"`
	Version     string          `json:"version"`
	Label       string          `json:"label"`
	Description string          `json:"description"`
	Tags        json.RawMessage `json:"tags"`
	Type        string          `json:"type"`
	Senders     json.RawMessage `json:"senders"`
	Receivers   json.RawMessage `json:"receivers"`
	Controls    json.RawMessage `json:"controls"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) error {
	_, err := q.db.ExecContext(ctx, createDevice,
		arg.ID,
		arg.ApiVersion,
		arg.NodeID,
		arg.Version,
		arg.Label,
		arg.Description,
		arg.Tags,
		arg.Type,
		arg.Senders,
		arg.Receivers,
		arg.Controls,
	)
	return err
}

const createFlow = `-- name: CreateFlow :exec
INSERT INTO flows (
    id, api_version, source_id, device_id, version, label, description, tags, format, media_type,
    sample_rate, bit_depth, DID_SDID, grain_rate, frame_width, frame_height,
    interlace_mode, colorspace, components, transfer_characteristic
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6,
    ?7, ?8, ?9, ?10,
    ?11, ?12, ?13, ?14,
    ?15, ?16, ?17, ?18,
    ?19, ?20
)
`

type CreateFlowParams struct {
	ID                     string          `json:"id"`
	ApiVersion             string          `json:"api_version"`
	SourceID               string          `json:"source_id"`
	DeviceID               string          `json:"device_id"`
	Version                string          `json:"version"`
	Label                  string          `json:"label"`
	Description            string          `json:"description"`
	Tags                   json.RawMessage `json:"tags"`
	Format                 string          `json:"format"`
	MediaType              sql.NullString  `json:"media_type"`
	SampleRate             json.RawMessage `json:"sample_rate"`
	BitDepth               sql.NullInt64   `json:"bit_depth"`
	DidSdid                json.RawMessage `json:"did_sdid"`
	GrainRate              json.RawMessage `json:"grain_rate"`
	FrameWidth             sql.NullInt64   `json:"frame_width"`
	FrameHeight            sql.NullInt64   `json:"frame_height"`
	InterlaceMode          sql.NullString  `json:"interlace_mode"`
	Colorspace             sql.NullString  `json:"colorspace"`
	Components             json.RawMessage `json:"components"`
	TransferCharacteristic sql.NullString  `json:"transfer_characteristic"`
}

func (q *Queries) CreateFlow(ctx context.Context, arg CreateFlowParams) error {
	_, err := q.db.ExecContext(ctx, createFlow,
		arg.ID,
		arg.ApiVersion,
		arg.SourceID,
		arg.DeviceID,
		arg.Version,
		arg.Label,
		arg.Description,
		arg.Tags,
		arg.Format,
		arg.MediaType,
		arg.SampleRate,
		arg.BitDepth,
		arg.DidSdid,
		arg.GrainRate,
		arg.FrameWidth,
		arg.FrameHeight,
		arg.InterlaceMode,
		arg.Colorspace,
		arg.Components,
		arg.TransferCharacteristic,
	)
	return err
}

const createNode = `-- name: CreateNode :exec
INSERT INTO nodes (
    id, api_version, version, label, description, tags, href, hostname, api, caps, services, clocks, interfaces, last_seen
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6,
    ?7, ?8, ?9, ?10, ?11,
    ?12, ?13, ?14
)
`

type CreateNodeParams struct {
	ID          string          `json:"id"`
	ApiVersion  string          `json:"api_version"`
	Version     string          `json:"version"`
	Label       string          `json:"label"`
	Description string          `json:"description"`
	Tags        json.RawMessage `json:"tags"`
	Href        string          `json:"href"`
	Hostname    sql.NullString  `json:"hostname"`
	Api         json.RawMessage `json:"api"`
	Caps        json.RawMessage `json:"caps"`
	Services    json.RawMessage `json:"services"`
	Clocks      json.RawMessage `json:"clocks"`
	Interfaces  json.RawMessage `json:"interfaces"`
	LastSeen    sql.NullTime    `json:"last_seen"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) error {
	_, err := q.db.ExecContext(ctx, createNode,
		arg.ID,
		arg.ApiVersion,
		arg.Version,
		arg.Label,
		arg.Description,
		arg.Tags,
		arg.Href,
		arg.Hostname,
		arg.Api,
		arg.Caps,
		arg.Services,
		arg.Clocks,
		arg.Interfaces,
		arg.LastSeen,
	)
	return err
}

const createReceiver = `-- name: CreateReceiver :exec
INSERT INTO receivers (
    id, api_version, device_id, version, label, description, tags, transport, format, caps,
    interface_bindings, subscription_sender_id, subscription_active
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6,
    ?7, ?8, ?9, ?10,
    ?11, ?12, ?13
)
`

type CreateReceiverParams struct {
	ID                   string          `json:"id"`
	ApiVersion           string          `json:"api_version"`
	DeviceID             string          `json:"device_id"`
	Version              string          `json:"version"`
	Label                string          `json:"label"`
	Description          string          `json:"description"`
	Tags                 json.RawMessage `json:"tags"`
	Transport            string          `json:"transport"`
	Format               string          `json:"format"`
	Caps                 json.RawMessage `json:"caps"`
	InterfaceBindings    json.RawMessage `json:"interface_bindings"`
	SubscriptionSenderID sql.NullString  `json:"subscription_sender_id"`
	SubscriptionActive   sql.NullBool    `json:"subscription_active"`
}

func (q *Queries) CreateReceiver(ctx context.Context, arg CreateReceiverParams) error {
	_, err := q.db.ExecContext(ctx, createReceiver,
		arg.ID,
		arg.ApiVersion,
		arg.DeviceID,
		arg.Version,
		arg.Label,
		arg.Description,
		arg.Tags,
		arg.Transport,
		arg.Format,
		arg.Caps,
		arg.InterfaceBindings,
		arg.SubscriptionSenderID,
		arg.SubscriptionActive,
	)
	return err
}

const createSender = `-- name: CreateSender :exec
INSERT INTO senders (
    id, api_version, device_id, flow_id, version, label, description, tags, transport,
    manifest_href, interface_bindings, subscription_receiver_id, subscription_active
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6,
    ?7, ?8, ?9, ?10,
    ?11, ?12, ?13
)
`

type CreateSenderParams struct {
	ID                     string          `json:"id"`
	ApiVersion             string          `json:"api_version"`
	DeviceID               string          `json:"device_id"`
	FlowID                 sql.NullString  `json:"flow_id"`
	Version                string          `json:"version"`
	Label                  string          `json:"label"`
	Description            string          `json:"description"`
	Tags                   json.RawMessage `json:"tags"`
	Transport              string          `json:"transport"`
	ManifestHref           sql.NullString  `json:"manifest_href"`
	InterfaceBindings      json.RawMessage `json:"interface_bindings"`
	SubscriptionReceiverID sql.NullString  `json:"subscription_receiver_id"`
	SubscriptionActive     sql.NullBool    `json:"subscription_active"`
}

func (q *Queries) CreateSender(ctx context.Context, arg CreateSenderParams) error {
	_, err := q.db.ExecContext(ctx, createSender,
		arg.ID,
		arg.ApiVersion,
		arg.DeviceID,
		arg.FlowID,
		arg.Version,
		arg.Label,
		arg.Description,
		arg.Tags,
		arg.Transport,
		arg.ManifestHref,
		arg.InterfaceBindings,
		arg.SubscriptionReceiverID,
		arg.SubscriptionActive,
	)
	return err
}

const createSource = `-- name: CreateSource :exec
INSERT INTO sources (
    id, api_version, device_id, version, label, description, tags, grain_rate, format, caps, parents, clock_name
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6,
    ?7, ?8, ?9, ?10, ?11, ?12
)
`

type CreateSourceParams struct {
	ID          string          `json:"id"`
	ApiVersion  string          `json:"api_version"`
	DeviceID    string          `json:"device_id"`
	Version     string          `json:"version"`
	Label       string          `json:"label"`
	Description string          `json:"description"`
	Tags        json.RawMessage `json:"tags"`
	GrainRate   json.RawMessage `json:"grain_rate"`
	Format      string          `json:"format"`
	Caps        json.RawMessage `json:"caps"`
	Parents     json.RawMessage `json:"parents"`
	ClockName   sql.NullString  `json:"clock_name"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) error {
	_, err := q.db.ExecContext(ctx, createSource,
		arg.ID,
		arg.ApiVersion,
		arg.DeviceID,
		arg.Version,
		arg.Label,
		arg.Description,
		arg.Tags,
		arg.GrainRate,
		arg.Format,
		arg.Caps,
		arg.Parents,
		arg.ClockName,
	)
	return err
}

const createSubscription = `-- name: CreateSubscription :exec
INSERT INTO subscriptions (
    id, resource_path, params, max_update_rate_ms, persist, secure_websocket, ws_href
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7
)
`

type CreateSubscriptionParams struct {
	ID              string          `json:"id"`
	ResourcePath    string          `json:"resource_path"`
	Params          json.RawMessage `json:"params"`
	MaxUpdateRateMs sql.NullInt64   `json:"max_update_rate_ms"`
	Persist         sql.NullBool    `json:"persist"`
	SecureWebsocket sql.NullBool    `json:"secure_websocket"`
	WsHref          sql.NullString  `json:"ws_href"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, createSubscription,
		arg.ID,
		arg.ResourcePath,
		arg.Params,
		arg.MaxUpdateRateMs,
		arg.Persist,
		arg.SecureWebsocket,
		arg.WsHref,
	)
	return err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = ?1
`

func (q *Queries) DeleteDevice(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDevice, id)
	return err
}

const deleteFlow = `-- name: DeleteFlow :exec
DELETE FROM flows WHERE id = ?1
`

func (q *Queries) DeleteFlow(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFlow, id)
	return err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes WHERE id = ?1
`

func (q *Queries) DeleteNode(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNode, id)
	return err
}

const deleteReceiver = `-- name: DeleteReceiver :exec
DELETE FROM receivers WHERE id = ?1
`

func (q *Queries) DeleteReceiver(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteReceiver, id)
	return err
}

const deleteSender = `-- name: DeleteSender :exec
DELETE FROM senders WHERE id = ?1
`

func (q *Queries) DeleteSender(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSender, id)
	return err
}

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM sources WHERE id = ?1
`

func (q *Queries) DeleteSource(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSource, id)
	return err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions WHERE id = ?1
`

func (q *Queries) DeleteSubscription(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSubscription, id)
	return err
}

const getDevice = `-- name: GetDevice :one
SELECT id, api_version, node_id, version, label, description, tags, type, senders, receivers, controls FROM devices WHERE id = ?1
`

func (q *Queries) GetDevice(ctx context.Context, id string) (Devices, error) {
	row := q.db.QueryRowContext(ctx, getDevice, id)
	var i Devices
	err := row.Scan(
		&i.ID,
		&i.ApiVersion,
		&i.NodeID,
		&i.Version,
		&i.Label,
		&i.Description,
		&i.Tags,
		&i.Type,
		&i.Senders,
		&i.Receivers,
		&i.Controls,
	)
	return i, err
}

const getExpiredNodes = `-- name: GetExpiredNodes :many
SELECT id FROM nodes WHERE last_seen < ?1
`

func (q *Queries) GetExpiredNodes(ctx context.Context, expirationTime sql.NullTime) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getExpiredNodes, expirationTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlow = `-- name: GetFlow :one
SELECT id, api_version, source_id, device_id, version, label, description, tags, format, media_type, sample_rate, bit_depth, did_sdid, grain_rate, frame_width, frame_height, interlace_mode, colorspace, components, transfer_characteristic FROM flows WHERE id = ?1
`

func (q *Queries) GetFlow(ctx context.Context, id string) (Flows, error) {
	row := q.db.QueryRowContext(ctx, getFlow, id)
	var i Flows
	err := row.Scan(
		&i.ID,
		&i.ApiVersion,
		&i.SourceID,
		&i.DeviceID,
		&i.Version,
		&i.Label,
		&i.Description,
		&i.Tags,
		&i.Format,
		&i.MediaType,
		&i.SampleRate,
		&i.BitDepth,
		&i.DidSdid,
		&i.GrainRate,
		&i.FrameWidth,
		&i.FrameHeight,
		&i.InterlaceMode,
		&i.Colorspace,
		&i.Components,
		&i.TransferCharacteristic,
	)
	return i, err
}

const getNode = `-- name: GetNode :one
SELECT id, api_version, version, label, description, tags, href, hostname, api, caps, services, clocks, interfaces, last_seen FROM nodes WHERE id = ?1
`

func (q *Queries) GetNode(ctx context.Context, id string) (Nodes, error) {
	row := q.db.QueryRowContext(ctx, getNode, id)
	var i Nodes
	err := row.Scan(
		&i.ID,
		&i.ApiVersion,
		&i.Version,
		&i.Label,
		&i.Description,
		&i.Tags,
		&i.Href,
		&i.Hostname,
		&i.Api,
		&i.Caps,
		&i.Services,
		&i.Clocks,
		&i.Interfaces,
		&i.LastSeen,
	)
	return i, err
}

const getReceiver = `-- name: GetReceiver :one
SELECT id, api_version, device_id, version, label, description, tags, transport, format, caps, interface_bindings, subscription_sender_id, subscription_active FROM receivers WHERE id = ?1
`

func (q *Queries) GetReceiver(ctx context.Context, id string) (Receivers, error) {
	row := q.db.QueryRowContext(ctx, getReceiver, id)
	var i Receivers
	err := row.Scan(
		&i.ID,
		&i.ApiVersion,
		&i.DeviceID,
		&i.Version,
		&i.Label,
		&i.Description,
		&i.Tags,
		&i.Transport,
		&i.Format,
		&i.Caps,
		&i.InterfaceBindings,
		&i.SubscriptionSenderID,
		&i.SubscriptionActive,
	)
	return i, err
}

const getSender = `-- name: GetSender :one
SELECT id, api_version, device_id, flow_id, version, label, description, tags, transport, manifest_href, interface_bindings, subscription_receiver_id, subscription_active FROM senders WHERE id = ?1
`

func (q *Queries) GetSender(ctx context.Context, id string) (Senders, error) {
	row := q.db.QueryRowContext(ctx, getSender, id)
	var i Senders
	err := row.Scan(
		&i.ID,
		&i.ApiVersion,
		&i.DeviceID,
		&i.FlowID,
		&i.Version,
		&i.Label,
		&i.Description,
		&i.Tags,
		&i.Transport,
		&i.ManifestHref,
		&i.InterfaceBindings,
		&i.SubscriptionReceiverID,
		&i.SubscriptionActive,
	)
	return i, err
}

const getSource = `-- name: GetSource :one
SELECT id, api_version, device_id, version, label, description, tags, grain_rate, format, caps, parents, clock_name FROM sources WHERE id = ?1
`

func (q *Queries) GetSource(ctx context.Context, id string) (Sources, error) {
	row := q.db.QueryRowContext(ctx, getSource, id)
	var i Sources
	err := row.Scan(
		&i.ID,
		&i.ApiVersion,
		&i.DeviceID,
		&i.Version,
		&i.Label,
		&i.Description,
		&i.Tags,
		&i.GrainRate,
		&i.Format,
		&i.Caps,
		&i.Parents,
		&i.ClockName,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, resource_path, params, max_update_rate_ms, persist, secure_websocket, ws_href FROM subscriptions WHERE id = ?1
`

func (q *Queries) GetSubscription(ctx context.Context, id string) (Subscriptions, error) {
	row := q.db.QueryRowContext(ctx, getSubscription, id)
	var i Subscriptions
	err := row.Scan(
		&i.ID,
		&i.ResourcePath,
		&i.Params,
		&i.MaxUpdateRateMs,
		&i.Persist,
		&i.SecureWebsocket,
		&i.WsHref,
	)
	return i, err
}

const iDExistsInDevices = `-- name: IDExistsInDevices :one
SELECT COUNT(*) FROM devices WHERE id = ?1
`

func (q *Queries) IDExistsInDevices(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, iDExistsInDevices, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const iDExistsInFlows = `-- name: IDExistsInFlows :one
SELECT COUNT(*) FROM flows WHERE id = ?1
`

func (q *Queries) IDExistsInFlows(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, iDExistsInFlows, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const iDExistsInNodes = `-- name: IDExistsInNodes :one
SELECT COUNT(*) FROM nodes WHERE id = ?1
`

func (q *Queries) IDExistsInNodes(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, iDExistsInNodes, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const iDExistsInReceivers = `-- name: IDExistsInReceivers :one
SELECT COUNT(*) FROM receivers WHERE id = ?1
`

func (q *Queries) IDExistsInReceivers(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, iDExistsInReceivers, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const iDExistsInSenders = `-- name: IDExistsInSenders :one
SELECT COUNT(*) FROM senders WHERE id = ?1
`

func (q *Queries) IDExistsInSenders(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, iDExistsInSenders, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const iDExistsInSources = `-- name: IDExistsInSources :one
SELECT COUNT(*) FROM sources WHERE id = ?1
`

func (q *Queries) IDExistsInSources(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, iDExistsInSources, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, api_version, node_id, version, label, description, tags, type, senders, receivers, controls FROM devices
`

func (q *Queries) ListDevices(ctx context.Context) ([]Devices, error) {
	rows, err := q.db.QueryContext(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Devices
	for rows.Next() {
		var i Devices
		if err := rows.Scan(
			&i.ID,
			&i.ApiVersion,
			&i.NodeID,
			&i.Version,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.Type,
			&i.Senders,
			&i.Receivers,
			&i.Controls,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByNode = `-- name: ListDevicesByNode :many
SELECT id, api_version, node_id, version, label, description, tags, type, senders, receivers, controls FROM devices WHERE node_id = ?1
`

func (q *Queries) ListDevicesByNode(ctx context.Context, nodeID string) ([]Devices, error) {
	rows, err := q.db.QueryContext(ctx, listDevicesByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Devices
	for rows.Next() {
		var i Devices
		if err := rows.Scan(
			&i.ID,
			&i.ApiVersion,
			&i.NodeID,
			&i.Version,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.Type,
			&i.Senders,
			&i.Receivers,
			&i.Controls,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlows = `-- name: ListFlows :many
SELECT id, api_version, source_id, device_id, version, label, description, tags, format, media_type, sample_rate, bit_depth, did_sdid, grain_rate, frame_width, frame_height, interlace_mode, colorspace, components, transfer_characteristic FROM flows
`

func (q *Queries) ListFlows(ctx context.Context) ([]Flows, error) {
	rows, err := q.db.QueryContext(ctx, listFlows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flows
	for rows.Next() {
		var i Flows
		if err := rows.Scan(
			&i.ID,
			&i.ApiVersion,
			&i.SourceID,
			&i.DeviceID,
			&i.Version,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.Format,
			&i.MediaType,
			&i.SampleRate,
			&i.BitDepth,
			&i.DidSdid,
			&i.GrainRate,
			&i.FrameWidth,
			&i.FrameHeight,
			&i.InterlaceMode,
			&i.Colorspace,
			&i.Components,
			&i.TransferCharacteristic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlowsByDevice = `-- name: ListFlowsByDevice :many
SELECT id, api_version, source_id, device_id, version, label, description, tags, format, media_type, sample_rate, bit_depth, did_sdid, grain_rate, frame_width, frame_height, interlace_mode, colorspace, components, transfer_characteristic FROM flows WHERE device_id = ?1
`

func (q *Queries) ListFlowsByDevice(ctx context.Context, deviceID string) ([]Flows, error) {
	rows, err := q.db.QueryContext(ctx, listFlowsByDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flows
	for rows.Next() {
		var i Flows
		if err := rows.Scan(
			&i.ID,
			&i.ApiVersion,
			&i.SourceID,
			&i.DeviceID,
			&i.Version,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.Format,
			&i.MediaType,
			&i.SampleRate,
			&i.BitDepth,
			&i.DidSdid,
			&i.GrainRate,
			&i.FrameWidth,
			&i.FrameHeight,
			&i.InterlaceMode,
			&i.Colorspace,
			&i.Components,
			&i.TransferCharacteristic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlowsBySource = `-- name: ListFlowsBySource :many
SELECT id, api_version, source_id, device_id, version, label, description, tags, format, media_type, sample_rate, bit_depth, did_sdid, grain_rate, frame_width, frame_height, interlace_mode, colorspace, components, transfer_characteristic FROM flows WHERE source_id = ?1
`

func (q *Queries) ListFlowsBySource(ctx context.Context, sourceID string) ([]Flows, error) {
	rows, err := q.db.QueryContext(ctx, listFlowsBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flows
	for rows.Next() {
		var i Flows
		if err := rows.Scan(
			&i.ID,
			&i.ApiVersion,
			&i.SourceID,
			&i.DeviceID,
			&i.Version,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.Format,
			&i.MediaType,
			&i.SampleRate,
			&i.BitDepth,
			&i.DidSdid,
			&i.GrainRate,
			&i.FrameWidth,
			&i.FrameHeight,
			&i.InterlaceMode,
			&i.Colorspace,
			&i.Components,
			&i.TransferCharacteristic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodes = `-- name: ListNodes :many
SELECT id, api_version, version, label, description, tags, href, hostname, api, caps, services, clocks, interfaces, last_seen FROM nodes
`

func (q *Queries) ListNodes(ctx context.Context) ([]Nodes, error) {
	rows, err := q.db.QueryContext(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Nodes
	for rows.Next() {
		var i Nodes
		if err := rows.Scan(
			&i.ID,
			&i.ApiVersion,
			&i.Version,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.Href,
			&i.Hostname,
			&i.Api,
			&i.Caps,
			&i.Services,
			&i.Clocks,
			&i.Interfaces,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivers = `-- name: ListReceivers :many
SELECT id, api_version, device_id, version, label, description, tags, transport, format, caps, interface_bindings, subscription_sender_id, subscription_active FROM receivers
`

func (q *Queries) ListReceivers(ctx context.Context) ([]Receivers, error) {
	rows, err := q.db.QueryContext(ctx, listReceivers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Receivers
	for rows.Next() {
		var i Receivers
		if err := rows.Scan(
			&i.ID,
			&i.ApiVersion,
			&i.DeviceID,
			&i.Version,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.Transport,
			&i.Format,
			&i.Caps,
			&i.InterfaceBindings,
			&i.SubscriptionSenderID,
			&i.SubscriptionActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceiversByDevice = `-- name: ListReceiversByDevice :many
SELECT id, api_version, device_id, version, label, description, tags, transport, format, caps, interface_bindings, subscription_sender_id, subscription_active FROM receivers WHERE device_id = ?1
`

func (q *Queries) ListReceiversByDevice(ctx context.Context, deviceID string) ([]Receivers, error) {
	rows, err := q.db.QueryContext(ctx, listReceiversByDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Receivers
	for rows.Next() {
		var i Receivers
		if err := rows.Scan(
			&i.ID,
			&i.ApiVersion,
			&i.DeviceID,
			&i.Version,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.Transport,
			&i.Format,
			&i.Caps,
			&i.InterfaceBindings,
			&i.SubscriptionSenderID,
			&i.SubscriptionActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSenders = `-- name: ListSenders :many
SELECT id, api_version, device_id, flow_id, version, label, description, tags, transport, manifest_href, interface_bindings, subscription_receiver_id, subscription_active FROM senders
`

func (q *Queries) ListSenders(ctx context.Context) ([]Senders, error) {
	rows, err := q.db.QueryContext(ctx, listSenders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Senders
	for rows.Next() {
		var i Senders
		if err := rows.Scan(
			&i.ID,
			&i.ApiVersion,
			&i.DeviceID,
			&i.FlowID,
			&i.Version,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.Transport,
			&i.ManifestHref,
			&i.InterfaceBindings,
			&i.SubscriptionReceiverID,
			&i.SubscriptionActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSendersByDevice = `-- name: ListSendersByDevice :many
SELECT id, api_version, device_id, flow_id, version, label, description, tags, transport, manifest_href, interface_bindings, subscription_receiver_id, subscription_active FROM senders WHERE device_id = ?1
`

func (q *Queries) ListSendersByDevice(ctx context.Context, deviceID string) ([]Senders, error) {
	rows, err := q.db.QueryContext(ctx, listSendersByDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Senders
	for rows.Next() {
		var i Senders
		if err := rows.Scan(
			&i.ID,
			&i.ApiVersion,
			&i.DeviceID,
			&i.FlowID,
			&i.Version,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.Transport,
			&i.ManifestHref,
			&i.InterfaceBindings,
			&i.SubscriptionReceiverID,
			&i.SubscriptionActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSendersByFlow = `-- name: ListSendersByFlow :many
SELECT id, api_version, device_id, flow_id, version, label, description, tags, transport, manifest_href, interface_bindings, subscription_receiver_id, subscription_active FROM senders WHERE flow_id = ?1
`

func (q *Queries) ListSendersByFlow(ctx context.Context, flowID sql.NullString) ([]Senders, error) {
	rows, err := q.db.QueryContext(ctx, listSendersByFlow, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Senders
	for rows.Next() {
		var i Senders
		if err := rows.Scan(
			&i.ID,
			&i.ApiVersion,
			&i.DeviceID,
			&i.FlowID,
			&i.Version,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.Transport,
			&i.ManifestHref,
			&i.InterfaceBindings,
			&i.SubscriptionReceiverID,
			&i.SubscriptionActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many
SELECT id, api_version, device_id, version, label, description, tags, grain_rate, format, caps, parents, clock_name FROM sources
`

func (q *Queries) ListSources(ctx context.Context) ([]Sources, error) {
	rows, err := q.db.QueryContext(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sources
	for rows.Next() {
		var i Sources
		if err := rows.Scan(
			&i.ID,
			&i.ApiVersion,
			&i.DeviceID,
			&i.Version,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.GrainRate,
			&i.Format,
			&i.Caps,
			&i.Parents,
			&i.ClockName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourcesByDevice = `-- name: ListSourcesByDevice :many
SELECT id, api_version, device_id, version, label, description, tags, grain_rate, format, caps, parents, clock_name FROM sources WHERE device_id = ?1
`

func (q *Queries) ListSourcesByDevice(ctx context.Context, deviceID string) ([]Sources, error) {
	rows, err := q.db.QueryContext(ctx, listSourcesByDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sources
	for rows.Next() {
		var i Sources
		if err := rows.Scan(
			&i.ID,
			&i.ApiVersion,
			&i.DeviceID,
			&i.Version,
			&i.Label,
			&i.Description,
			&i.Tags,
			&i.GrainRate,
			&i.Format,
			&i.Caps,
			&i.Parents,
			&i.ClockName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, resource_path, params, max_update_rate_ms, persist, secure_websocket, ws_href FROM subscriptions
`

func (q *Queries) ListSubscriptions(ctx context.Context) ([]Subscriptions, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscriptions
	for rows.Next() {
		var i Subscriptions
		if err := rows.Scan(
			&i.ID,
			&i.ResourcePath,
			&i.Params,
			&i.MaxUpdateRateMs,
			&i.Persist,
			&i.SecureWebsocket,
			&i.WsHref,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDevice = `-- name: UpdateDevice :exec
UPDATE devices SET
    version = ?1, label = ?2, description = ?3,
    tags = ?4, type = ?5, senders = ?6,
    receivers = ?7, controls = ?8
WHERE id = ?9
`

type UpdateDeviceParams struct {
	Version     string          `json:"version"`
	Label       string          `json:"label"`
	Description string          `json:"description"`
	Tags        json.RawMessage `json:"tags"`
	Type        string          `json:"type"`
	Senders     json.RawMessage `json:"senders"`
	Receivers   json.RawMessage `json:"receivers"`
	Controls    json.RawMessage `json:"controls"`
	ID          string          `json:"id"`
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) error {
	_, err := q.db.ExecContext(ctx, updateDevice,
		arg.Version,
		arg.Label,
		arg.Description,
		arg.Tags,
		arg.Type,
		arg.Senders,
		arg.Receivers,
		arg.Controls,
		arg.ID,
	)
	return err
}

const updateFlow = `-- name: UpdateFlow :exec
UPDATE flows SET
    version = ?1, label = ?2, description = ?3,
    tags = ?4, format = ?5, media_type = ?6,
    sample_rate = ?7, bit_depth = ?8,
    DID_SDID = ?9, grain_rate = ?10,
    frame_width = ?11, frame_height = ?12,
    interlace_mode = ?13, colorspace = ?14,
    components = ?15, transfer_characteristic = ?16
WHERE id = ?17
`

type UpdateFlowParams struct {
	Version                string          `json:"version"`
	Label                  string          `json:"label"`
	Description            string          `json:"description"`
	Tags                   json.RawMessage `json:"tags"`
	Format                 string          `json:"format"`
	MediaType              sql.NullString  `json:"media_type"`
	SampleRate             json.RawMessage `json:"sample_rate"`
	BitDepth               sql.NullInt64   `json:"bit_depth"`
	DidSdid                json.RawMessage `json:"did_sdid"`
	GrainRate              json.RawMessage `json:"grain_rate"`
	FrameWidth             sql.NullInt64   `json:"frame_width"`
	FrameHeight            sql.NullInt64   `json:"frame_height"`
	InterlaceMode          sql.NullString  `json:"interlace_mode"`
	Colorspace             sql.NullString  `json:"colorspace"`
	Components             json.RawMessage `json:"components"`
	TransferCharacteristic sql.NullString  `json:"transfer_characteristic"`
	ID                     string          `json:"id"`
}

func (q *Queries) UpdateFlow(ctx context.Context, arg UpdateFlowParams) error {
	_, err := q.db.ExecContext(ctx, updateFlow,
		arg.Version,
		arg.Label,
		arg.Description,
		arg.Tags,
		arg.Format,
		arg.MediaType,
		arg.SampleRate,
		arg.BitDepth,
		arg.DidSdid,
		arg.GrainRate,
		arg.FrameWidth,
		arg.FrameHeight,
		arg.InterlaceMode,
		arg.Colorspace,
		arg.Components,
		arg.TransferCharacteristic,
		arg.ID,
	)
	return err
}

const updateNode = `-- name: UpdateNode :exec
UPDATE nodes SET
    version = ?1, label = ?2, description = ?3,
    tags = ?4, href = ?5, hostname = ?6,
    api = ?7, caps = ?8, services = ?9,
    clocks = ?10, interfaces = ?11, last_seen = ?12
WHERE id = ?13
`

type UpdateNodeParams struct {
	Version     string          `json:"version"`
	Label       string          `json:"label"`
	Description string          `json:"description"`
	Tags        json.RawMessage `json:"tags"`
	Href        string          `json:"href"`
	Hostname    sql.NullString  `json:"hostname"`
	Api         json.RawMessage `json:"api"`
	Caps        json.RawMessage `json:"caps"`
	Services    json.RawMessage `json:"services"`
	Clocks      json.RawMessage `json:"clocks"`
	Interfaces  json.RawMessage `json:"interfaces"`
	LastSeen    sql.NullTime    `json:"last_seen"`
	ID          string          `json:"id"`
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) error {
	_, err := q.db.ExecContext(ctx, updateNode,
		arg.Version,
		arg.Label,
		arg.Description,
		arg.Tags,
		arg.Href,
		arg.Hostname,
		arg.Api,
		arg.Caps,
		arg.Services,
		arg.Clocks,
		arg.Interfaces,
		arg.LastSeen,
		arg.ID,
	)
	return err
}

const updateNodeLastSeen = `-- name: UpdateNodeLastSeen :exec
UPDATE nodes SET last_seen = ?1 WHERE id = ?2
`

type UpdateNodeLastSeenParams struct {
	LastSeen sql.NullTime `json:"last_seen"`
	ID       string       `json:"id"`
}

func (q *Queries) UpdateNodeLastSeen(ctx context.Context, arg UpdateNodeLastSeenParams) error {
	_, err := q.db.ExecContext(ctx, updateNodeLastSeen, arg.LastSeen, arg.ID)
	return err
}

const updateReceiver = `-- name: UpdateReceiver :exec
UPDATE receivers SET
    version = ?1, label = ?2, description = ?3,
    tags = ?4, transport = ?5, format = ?6,
    caps = ?7, interface_bindings = ?8,
    subscription_sender_id = ?9,
    subscription_active = ?10
WHERE id = ?11
`

type UpdateReceiverParams struct {
	Version              string          `json:"version"`
	Label                string          `json:"label"`
	Description          string          `json:"description"`
	Tags                 json.RawMessage `json:"tags"`
	Transport            string          `json:"transport"`
	Format               string          `json:"format"`
	Caps                 json.RawMessage `json:"caps"`
	InterfaceBindings    json.RawMessage `json:"interface_bindings"`
	SubscriptionSenderID sql.NullString  `json:"subscription_sender_id"`
	SubscriptionActive   sql.NullBool    `json:"subscription_active"`
	ID                   string          `json:"id"`
}

func (q *Queries) UpdateReceiver(ctx context.Context, arg UpdateReceiverParams) error {
	_, err := q.db.ExecContext(ctx, updateReceiver,
		arg.Version,
		arg.Label,
		arg.Description,
		arg.Tags,
		arg.Transport,
		arg.Format,
		arg.Caps,
		arg.InterfaceBindings,
		arg.SubscriptionSenderID,
		arg.SubscriptionActive,
		arg.ID,
	)
	return err
}

const updateSender = `-- name: UpdateSender :exec
UPDATE senders SET
    version = ?1, label = ?2, description = ?3,
    tags = ?4, flow_id = ?5, transport = ?6,
    manifest_href = ?7, interface_bindings = ?8,
    subscription_receiver_id = ?9,
    subscription_active = ?10
WHERE id = ?11
`

type UpdateSenderParams struct {
	Version                string          `json:"version"`
	Label                  string          `json:"label"`
	Description            string          `json:"description"`
	Tags                   json.RawMessage `json:"tags"`
	FlowID                 sql.NullString  `json:"flow_id"`
	Transport              string          `json:"transport"`
	ManifestHref           sql.NullString  `json:"manifest_href"`
	InterfaceBindings      json.RawMessage `json:"interface_bindings"`
	SubscriptionReceiverID sql.NullString  `json:"subscription_receiver_id"`
	SubscriptionActive     sql.NullBool    `json:"subscription_active"`
	ID                     string          `json:"id"`
}

func (q *Queries) UpdateSender(ctx context.Context, arg UpdateSenderParams) error {
	_, err := q.db.ExecContext(ctx, updateSender,
		arg.Version,
		arg.Label,
		arg.Description,
		arg.Tags,
		arg.FlowID,
		arg.Transport,
		arg.ManifestHref,
		arg.InterfaceBindings,
		arg.SubscriptionReceiverID,
		arg.SubscriptionActive,
		arg.ID,
	)
	return err
}

const updateSource = `-- name: UpdateSource :exec
UPDATE sources SET
    version = ?1, label = ?2, description = ?3,
    tags = ?4, grain_rate = ?5, format = ?6,
    caps = ?7, parents = ?8, clock_name = ?9
WHERE id = ?10
`

type UpdateSourceParams struct {
	Version     string          `json:"version"`
	Label       string          `json:"label"`
	Description string          `json:"description"`
	Tags        json.RawMessage `json:"tags"`
	GrainRate   json.RawMessage `json:"grain_rate"`
	Format      string          `json:"format"`
	Caps        json.RawMessage `json:"caps"`
	Parents     json.RawMessage `json:"parents"`
	ClockName   sql.NullString  `json:"clock_name"`
	ID          string          `json:"id"`
}

func (q *Queries) UpdateSource(ctx context.Context, arg UpdateSourceParams) error {
	_, err := q.db.ExecContext(ctx, updateSource,
		arg.Version,
		arg.Label,
		arg.Description,
		arg.Tags,
		arg.GrainRate,
		arg.Format,
		arg.Caps,
		arg.Parents,
		arg.ClockName,
		arg.ID,
	)
	return err
}

const upsertDevice = `-- name: UpsertDevice :exec
INSERT INTO devices (
    id, api_version, node_id, version, label, description, tags, type, senders, receivers, controls
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6,
    ?7, ?8, ?9, ?10, ?11
)
ON CONFLICT(id) DO UPDATE SET
    api_version = excluded.api_version, node_id = excluded.node_id, version = excluded.version, label = excluded.label,
    description = excluded.description, tags = excluded.tags, type = excluded.type,
    senders = excluded.senders, receivers = excluded.receivers, controls = excluded.controls
`

type UpsertDeviceParams struct {
	ID          string          `json:"id"`
	ApiVersion  string          `json:"api_version"`
	NodeID      string          `json:"node_id"`
	Version     string          `json:"version"`
	Label       string          `json:"label"`
	Description string          `json:"description"`
	Tags        json.RawMessage `json:"tags"`
	Type        string          `json:"type"`
	Senders     json.RawMessage `json:"senders"`
	Receivers   json.RawMessage `json:"receivers"`
	Controls    json.RawMessage `json:"controls"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error {
	_, err := q.db.ExecContext(ctx, upsertDevice,
		arg.ID,
		arg.ApiVersion,
		arg.NodeID,
		arg.Version,
		arg.Label,
		arg.Description,
		arg.Tags,
		arg.Type,
		arg.Senders,
		arg.Receivers,
		arg.Controls,
	)
	return err
}

const upsertFlow = `-- name: UpsertFlow :exec
INSERT INTO flows (
    id, api_version, source_id, device_id, version, label, description, tags, format, media_type,
    sample_rate, bit_depth, DID_SDID, grain_rate, frame_width, frame_height,
    interlace_mode, colorspace, components, transfer_characteristic
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6,
    ?7, ?8, ?9, ?10,
    ?11, ?12, ?13, ?14,
    ?15, ?16, ?17, ?18,
    ?19, ?20
)
ON CONFLICT(id) DO UPDATE SET
    api_version = excluded.api_version, source_id = excluded.source_id, device_id = excluded.device_id, version = excluded.version,
    label = excluded.label, description = excluded.description, tags = excluded.tags,
    format = excluded.format, media_type = excluded.media_type, sample_rate = excluded.sample_rate,
    bit_depth = excluded.bit_depth, DID_SDID = excluded.DID_SDID, grain_rate = excluded.grain_rate,
    frame_width = excluded.frame_width, frame_height = excluded.frame_height,
    interlace_mode = excluded.interlace_mode, colorspace = excluded.colorspace,
    components = excluded.components, transfer_characteristic = excluded.transfer_characteristic
`

type UpsertFlowParams struct {
	ID                     string          `json:"id"`
	ApiVersion             string          `json:"api_version"`
	SourceID               string          `json:"source_id"`
	DeviceID               string          `json:"device_id"`
	Version                string          `json:"version"`
	Label                  string          `json:"label"`
	Description            string          `json:"description"`
	Tags                   json.RawMessage `json:"tags"`
	Format                 string          `json:"format"`
	MediaType              sql.NullString  `json:"media_type"`
	SampleRate             json.RawMessage `json:"sample_rate"`
	BitDepth               sql.NullInt64   `json:"bit_depth"`
	DidSdid                json.RawMessage `json:"did_sdid"`
	GrainRate              json.RawMessage `json:"grain_rate"`
	FrameWidth             sql.NullInt64   `json:"frame_width"`
	FrameHeight            sql.NullInt64   `json:"frame_height"`
	InterlaceMode          sql.NullString  `json:"interlace_mode"`
	Colorspace             sql.NullString  `json:"colorspace"`
	Components             json.RawMessage `json:"components"`
	TransferCharacteristic sql.NullString  `json:"transfer_characteristic"`
}

func (q *Queries) UpsertFlow(ctx context.Context, arg UpsertFlowParams) error {
	_, err := q.db.ExecContext(ctx, upsertFlow,
		arg.ID,
		arg.ApiVersion,
		arg.SourceID,
		arg.DeviceID,
		arg.Version,
		arg.Label,
		arg.Description,
		arg.Tags,
		arg.Format,
		arg.MediaType,
		arg.SampleRate,
		arg.BitDepth,
		arg.DidSdid,
		arg.GrainRate,
		arg.FrameWidth,
		arg.FrameHeight,
		arg.InterlaceMode,
		arg.Colorspace,
		arg.Components,
		arg.TransferCharacteristic,
	)
	return err
}

const upsertNode = `-- name: UpsertNode :exec
INSERT INTO nodes (
    id, api_version, version, label, description, tags, href, hostname, api, caps, services, clocks, interfaces, last_seen
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6,
    ?7, ?8, ?9, ?10, ?11,
    ?12, ?13, ?14
)
ON CONFLICT(id) DO UPDATE SET
    api_version = excluded.api_version, version = excluded.version, label = excluded.label, description = excluded.description,
    tags = excluded.tags, href = excluded.href, hostname = excluded.hostname,
    api = excluded.api, caps = excluded.caps, services = excluded.services,
    clocks = excluded.clocks, interfaces = excluded.interfaces, last_seen = excluded.last_seen
`

type UpsertNodeParams struct {
	ID          string          `json:"id"`
	ApiVersion  string          `json:"api_version"`
	Version     string          `json:"version"`
	Label       string          `json:"label"`
	Description string          `json:"description"`
	Tags        json.RawMessage `json:"tags"`
	Href        string          `json:"href"`
	Hostname    sql.NullString  `json:"hostname"`
	Api         json.RawMessage `json:"api"`
	Caps        json.RawMessage `json:"caps"`
	Services    json.RawMessage `json:"services"`
	Clocks      json.RawMessage `json:"clocks"`
	Interfaces  json.RawMessage `json:"interfaces"`
	LastSeen    sql.NullTime    `json:"last_seen"`
}

func (q *Queries) UpsertNode(ctx context.Context, arg UpsertNodeParams) error {
	_, err := q.db.ExecContext(ctx, upsertNode,
		arg.ID,
		arg.ApiVersion,
		arg.Version,
		arg.Label,
		arg.Description,
		arg.Tags,
		arg.Href,
		arg.Hostname,
		arg.Api,
		arg.Caps,
		arg.Services,
		arg.Clocks,
		arg.Interfaces,
		arg.LastSeen,
	)
	return err
}

const upsertReceiver = `-- name: UpsertReceiver :exec
INSERT INTO receivers (
    id, api_version, device_id, version, label, description, tags, transport, format, caps,
    interface_bindings, subscription_sender_id, subscription_active
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6,
    ?7, ?8, ?9, ?10,
    ?11, ?12, ?13
)
ON CONFLICT(id) DO UPDATE SET
    api_version = excluded.api_version, device_id = excluded.device_id, version = excluded.version, label = excluded.label,
    description = excluded.description, tags = excluded.tags, transport = excluded.transport,
    format = excluded.format, caps = excluded.caps, interface_bindings = excluded.interface_bindings,
    subscription_sender_id = excluded.subscription_sender_id,
    subscription_active = excluded.subscription_active
`

type UpsertReceiverParams struct {
	ID                   string          `json:"id"`
	ApiVersion           string          `json:"api_version"`
	DeviceID             string          `json:"device_id"`
	Version              string          `json:"version"`
	Label                string          `json:"label"`
	Description          string          `json:"description"`
	Tags                 json.RawMessage `json:"tags"`
	Transport            string          `json:"transport"`
	Format               string          `json:"format"`
	Caps                 json.RawMessage `json:"caps"`
	InterfaceBindings    json.RawMessage `json:"interface_bindings"`
	SubscriptionSenderID sql.NullString  `json:"subscription_sender_id"`
	SubscriptionActive   sql.NullBool    `json:"subscription_active"`
}

func (q *Queries) UpsertReceiver(ctx context.Context, arg UpsertReceiverParams) error {
	_, err := q.db.ExecContext(ctx, upsertReceiver,
		arg.ID,
		arg.ApiVersion,
		arg.DeviceID,
		arg.Version,
		arg.Label,
		arg.Description,
		arg.Tags,
		arg.Transport,
		arg.Format,
		arg.Caps,
		arg.InterfaceBindings,
		arg.SubscriptionSenderID,
		arg.SubscriptionActive,
	)
	return err
}

const upsertSender = `-- name: UpsertSender :exec
INSERT INTO senders (
    id, api_version, device_id, flow_id, version, label, description, tags, transport,
    manifest_href, interface_bindings, subscription_receiver_id, subscription_active
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6,
    ?7, ?8, ?9, ?10,
    ?11, ?12, ?13
)
ON CONFLICT(id) DO UPDATE SET
    api_version = excluded.api_version, device_id = excluded.device_id, flow_id = excluded.flow_id, version = excluded.version,
    label = excluded.label, description = excluded.description, tags = excluded.tags,
    transport = excluded.transport, manifest_href = excluded.manifest_href,
    interface_bindings = excluded.interface_bindings,
    subscription_receiver_id = excluded.subscription_receiver_id,
    subscription_active = excluded.subscription_active
`

type UpsertSenderParams struct {
	ID                     string          `json:"id"`
	ApiVersion             string          `json:"api_version"`
	DeviceID               string          `json:"device_id"`
	FlowID                 sql.NullString  `json:"flow_id"`
	Version                string          `json:"version"`
	Label                  string          `json:"label"`
	Description            string          `json:"description"`
	Tags                   json.RawMessage `json:"tags"`
	Transport              string          `json:"transport"`
	ManifestHref           sql.NullString  `json:"manifest_href"`
	InterfaceBindings      json.RawMessage `json:"interface_bindings"`
	SubscriptionReceiverID sql.NullString  `json:"subscription_receiver_id"`
	SubscriptionActive     sql.NullBool    `json:"subscription_active"`
}

func (q *Queries) UpsertSender(ctx context.Context, arg UpsertSenderParams) error {
	_, err := q.db.ExecContext(ctx, upsertSender,
		arg.ID,
		arg.ApiVersion,
		arg.DeviceID,
		arg.FlowID,
		arg.Version,
		arg.Label,
		arg.Description,
		arg.Tags,
		arg.Transport,
		arg.ManifestHref,
		arg.InterfaceBindings,
		arg.SubscriptionReceiverID,
		arg.SubscriptionActive,
	)
	return err
}

const upsertSource = `-- name: UpsertSource :exec
INSERT INTO sources (
    id, api_version, device_id, version, label, description, tags, grain_rate, format, caps, parents, clock_name
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6,
    ?7, ?8, ?9, ?10, ?11, ?12
)
ON CONFLICT(id) DO UPDATE SET
    api_version = excluded.api_version, device_id = excluded.device_id, version = excluded.version, label = excluded.label,
    description = excluded.description, tags = excluded.tags, grain_rate = excluded.grain_rate,
    format = excluded.format, caps = excluded.caps, parents = excluded.parents,
    clock_name = excluded.clock_name
`

type UpsertSourceParams struct {
	ID          string          `json:"id"`
	ApiVersion  string          `json:"api_version"`
	DeviceID    string          `json:"device_id"`
	Version     string          `json:"version"`
	Label       string          `json:"label"`
	Description string          `json:"description"`
	Tags        json.RawMessage `json:"tags"`
	GrainRate   json.RawMessage `json:"grain_rate"`
	Format      string          `json:"format"`
	Caps        json.RawMessage `json:"caps"`
	Parents     json.RawMessage `json:"parents"`
	ClockName   sql.NullString  `json:"clock_name"`
}

func (q *Queries) UpsertSource(ctx context.Context, arg UpsertSourceParams) error {
	_, err := q.db.ExecContext(ctx, upsertSource,
		arg.ID,
		arg.ApiVersion,
		arg.DeviceID,
		arg.Version,
		arg.Label,
		arg.Description,
		arg.Tags,
		arg.GrainRate,
		arg.Format,
		arg.Caps,
		arg.Parents,
		arg.ClockName,
	)
	return err
}

const upsertSubscription = `-- name: UpsertSubscription :exec
INSERT INTO subscriptions (
    id, resource_path, params, max_update_rate_ms, persist, secure_websocket, ws_href
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7
)
ON CONFLICT(id) DO UPDATE SET
    resource_path = excluded.resource_path, params = excluded.params,
    max_update_rate_ms = excluded.max_update_rate_ms, persist = excluded.persist,
    secure_websocket = excluded.secure_websocket, ws_href = excluded.ws_href
`

type UpsertSubscriptionParams struct {
	ID              string          `json:"id"`
	ResourcePath    string          `json:"resource_path"`
	Params          json.RawMessage `json:"params"`
	MaxUpdateRateMs sql.NullInt64   `json:"max_update_rate_ms"`
	Persist         sql.NullBool    `json:"persist"`
	SecureWebsocket sql.NullBool    `json:"secure_websocket"`
	WsHref          sql.NullString  `json:"ws_href"`
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSubscription,
		arg.ID,
		arg.ResourcePath,
		arg.Params,
		arg.MaxUpdateRateMs,
		arg.Persist,
		arg.SecureWebsocket,
		arg.WsHref,
	)
	return err
}
